# Generated by Django 5.2.16 on 2026-08-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0003_activity_expected_participants"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="objective",
            field=models.TextField(
                blank=True,
                help_text="What this project is trying to achieve -- the part of the programme it delivers.",
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="programmes.activity",
            ),
        ),
    ]
