# Generated by Django 5.2.16 on 2026-08-13 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_category_document_description_and_more"),
        ("governance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resolution",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="governanceofficial",
            name="resignation_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Resignation letter, board resolution or other supporting evidence.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="resolution",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resolution",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="The formal signed resolution document, if one was captured.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="resolution",
            name="reference_number",
            field=models.CharField(
                blank=True, help_text="e.g. BR-2026-01", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="resolution",
            name="decision",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("deferred", "Deferred"),
                    ("noted", "Noted"),
                ],
                default="approved",
                max_length=15,
            ),
        ),
    ]
