# Generated by Django 5.2.16 on 2026-07-23 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("networks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("funding", "Funding"),
                            ("training", "Training"),
                            ("grant", "Grant"),
                            ("tender", "Tender"),
                            ("partnership", "Partnership"),
                            ("event", "Event"),
                            ("capacity", "Capacity Development"),
                        ],
                        default="funding",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("eligibility", models.TextField(blank=True)),
                ("opening_date", models.DateField(blank=True, null=True)),
                ("closing_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("external_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("target_sectors", models.JSONField(blank=True, default=list)),
                ("target_provinces", models.JSONField(blank=True, default=list)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="networks.network",
                    ),
                ),
            ],
            options={
                "ordering": ["-opening_date"],
            },
        ),
    ]
