# Generated by Django 5.2.16 on 2026-08-14 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        ("monitoring_evaluation", "0001_initial"),
        ("programmes", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="budget_line",
            field=models.ForeignKey(
                blank=True,
                help_text="What this activity costs against the project's budget, if tracked at this level.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="expenses.budgetline",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="outputs",
            field=models.ManyToManyField(
                blank=True,
                help_text="What this activity produces -- indicators are then reached via the Output's own Outcome.",
                related_name="activities",
                to="monitoring_evaluation.output",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="responsible_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Who delivers this activity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="need_and_background",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="staffing_plan",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="wizard_step",
            field=models.CharField(
                choices=[
                    ("programme", "Programme"),
                    ("why", "Why"),
                    ("who_and_where", "Who & Where"),
                    ("success", "What Success Looks Like"),
                    ("projects_and_activities", "Projects & Activities"),
                    ("people_and_resources", "People & Resources"),
                    ("budget_and_funding", "Budget & Funding"),
                    ("review", "Review & Create"),
                    ("complete", "Complete"),
                ],
                default="programme",
                max_length=25,
            ),
        ),
    ]
