# Generated by Django 5.2.16 on 2026-08-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0002_activity_budget_line_activity_outputs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="expected_participants",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Planned headcount, for comparison against actual attendance.",
                null=True,
            ),
        ),
    ]
