# Generated by Django 5.2.16 on 2026-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0004_programmemembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EC", "Eastern Cape"),
                    ("FS", "Free State"),
                    ("GP", "Gauteng"),
                    ("KZN", "KwaZulu-Natal"),
                    ("LP", "Limpopo"),
                    ("MP", "Mpumalanga"),
                    ("NC", "Northern Cape"),
                    ("NW", "North West"),
                    ("WC", "Western Cape"),
                ],
                help_text="Primary province. Finer geography (district, municipality, locality, venue) goes in Locations below.",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="programme_area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("education_skills", "Education & Skills Development"),
                    ("youth_development", "Youth Development"),
                    ("children_families", "Children & Families"),
                    ("health", "Health"),
                    ("disability", "Disability"),
                    ("older_persons", "Older Persons"),
                    ("community_development", "Community Development"),
                    ("social_crime_prevention", "Social Crime Prevention"),
                    ("gender_based_violence", "Gender-Based Violence"),
                    ("food_security", "Food Security"),
                    ("other", "Other"),
                ],
                max_length=150,
            ),
        ),
    ]
