# Generated by Django 5.2.16 on 2026-08-14 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_category_document_description_and_more"),
        ("programmes", "0005_programme_province_alter_programme_programme_area"),
        ("projects", "0003_projectmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="toc_change",
            field=models.TextField(blank=True, help_text="What change do we expect?"),
        ),
        migrations.AddField(
            model_name="programme",
            name="toc_what",
            field=models.TextField(blank=True, help_text="What are we doing?"),
        ),
        migrations.AddField(
            model_name="programme",
            name="toc_why",
            field=models.TextField(
                blank=True,
                help_text="Why do we believe this will contribute to that change?",
            ),
        ),
        migrations.CreateModel(
            name="Assumption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("statement", models.TextField()),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("being_tested", "Being tested"),
                            ("no_longer_valid", "No longer valid"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assumptions",
                        to="programmes.programme",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContextNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("funding_environment", "Funding environment changed"),
                            ("school_calendar", "School calendar changed"),
                            ("community_conditions", "Community conditions changed"),
                            ("policy", "Policy changed"),
                            ("stakeholder", "Stakeholder changed"),
                            (
                                "employment_environment",
                                "Employment environment changed",
                            ),
                            ("venue", "Venue became unavailable"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=25,
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_notes",
                        to="programmes.programme",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningLogEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("challenge", "Challenge"),
                            ("unexpected_result", "Unexpected result"),
                            ("context_change", "Context change"),
                            ("stakeholder_change", "Stakeholder change"),
                            ("opportunity", "Opportunity"),
                            ("setback", "Setback"),
                        ],
                        max_length=20,
                    ),
                ),
                ("what_happened", models.TextField()),
                ("what_changed", models.TextField(blank=True)),
                ("what_we_learned", models.TextField(blank=True)),
                ("action_we_will_take", models.TextField(blank=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_log_entries",
                        to="programmes.activity",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_log_entries",
                        to="documents.document",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_log_entries",
                        to="programmes.programme",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_log_entries",
                        to="projects.project",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Learning log entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("why_it_matters", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("learning", "Learning"),
                            ("answered", "Answered"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("answer_note", models.TextField(blank=True)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_questions",
                        to="programmes.programme",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
