# Generated by Django 5.2.16 on 2026-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0006_programme_toc_change_programme_toc_what_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="toc_change",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="programme",
            name="toc_what",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="programme",
            name="toc_why",
            field=models.TextField(blank=True),
        ),
    ]
