# Generated by Django 5.2.16 on 2026-08-13 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("template", "Template"),
                            ("policy", "Policy"),
                            ("checklist", "Checklist"),
                            ("toolkit", "Toolkit"),
                            ("video", "Video"),
                            ("link", "Link"),
                            ("report", "Report"),
                            ("training_material", "Training Material"),
                        ],
                        default="guide",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Subject area, e.g. Governance, Compliance, M&E (free text -- kept light on purpose for V1).",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, upload_to="resources/%Y/%m/")),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Used for the Link type, or alongside a file as a source link.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-published_at", "-created_at"],
            },
        ),
    ]
