# Generated by Django 5.2.16 on 2026-08-13 04:48

import apps.core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("documents", "0001_initial"),
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("organisation", "Organisation"),
                    ("governance", "Governance"),
                    ("compliance", "Compliance"),
                    ("programmes", "Programmes"),
                    ("finance", "Finance"),
                    ("partnerships", "Partnerships"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_by_set",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=apps.core.storage.PrivateFileSystemStorage(
                    location="/home/user/ANNET-Digital-Network-NPO-Operating-Platform/private_media"
                ),
                upload_to="documents/%Y/%m/",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organisation", "status"], name="documents_d_organis_9df828_idx"
            ),
        ),
    ]
