# Generated by Django 5.2.16 on 2026-07-23 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("funder_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="ZAR", max_length=3)),
                ("funding_start", models.DateField(blank=True, null=True)),
                ("funding_end", models.DateField(blank=True, null=True)),
                ("reporting_requirements", models.TextField(blank=True)),
                ("restrictions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("opportunity", "Opportunity"),
                            ("application", "Application"),
                            ("awarded", "Awarded"),
                            ("agreement", "Agreement"),
                            ("active", "Active"),
                            ("reporting", "Reporting"),
                            ("closeout", "Closeout"),
                            ("closed", "Closed"),
                        ],
                        default="opportunity",
                        max_length=15,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "responsible_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
