# Generated by Django 5.2.16 on 2026-07-23 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComplianceEvidence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComplianceObligation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("ready_for_submission", "Ready for Submission"),
                            ("submitted", "Submitted"),
                            ("evidence_recorded", "Evidence Recorded"),
                            ("overdue", "Overdue"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="not_started",
                        max_length=25,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("submitted_at", models.DateField(blank=True, null=True)),
                ("submission_reference", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        help_text="e.g. DSD, CIPC, SARS, POPIA, Master's Office",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "applicable_entity_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Organisation.organisation_type / legal_structure values this rule applies to, e.g. ['npc']",
                    ),
                ),
                (
                    "required_registration_statuses",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Organisation boolean fields that must be true, e.g. {"dsd_registered": true}',
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("fixed_date", "Fixed date each period"),
                            (
                                "financial_year_relative",
                                "Relative to financial year end",
                            ),
                            ("anniversary", "Anniversary of registration/founding"),
                            ("event_triggered", "Event-triggered"),
                        ],
                        default="financial_year_relative",
                        max_length=30,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once-off"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("biennial", "Every two years"),
                            ("event", "As triggered by an event"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                (
                    "deadline_rule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"months_after_fy_end": 6} or {"fixed_month_day": "08-31"} or {"days_after_anniversary": 30}',
                    ),
                ),
                (
                    "evidence_requirements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of evidence item descriptions",
                    ),
                ),
                (
                    "responsible_role",
                    models.CharField(
                        blank=True,
                        help_text="Suggested org role, e.g. compliance_officer",
                        max_length=30,
                    ),
                ),
                (
                    "official_source",
                    models.CharField(
                        blank=True,
                        help_text="Reference/URL to the authoritative source",
                        max_length=500,
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateField(
                        blank=True,
                        help_text="When this rule's content was last checked against the official source",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["authority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceStatusEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("ready_for_submission", "Ready for Submission"),
                            ("submitted", "Submitted"),
                            ("evidence_recorded", "Evidence Recorded"),
                            ("overdue", "Overdue"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        max_length=25,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
