# Generated by Django 5.2.16 on 2026-07-23 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance", "0001_initial"),
        ("documents", "0001_initial"),
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceevidence",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_evidence",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="complianceevidence",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceobligation",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_obligations",
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="complianceobligation",
            name="responsible_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceevidence",
            name="obligation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_items",
                to="compliance.complianceobligation",
            ),
        ),
        migrations.AddField(
            model_name="complianceobligation",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="obligations",
                to="compliance.compliancerule",
            ),
        ),
        migrations.AddField(
            model_name="compliancestatusevent",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compliancestatusevent",
            name="obligation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_events",
                to="compliance.complianceobligation",
            ),
        ),
        migrations.AddIndex(
            model_name="complianceobligation",
            index=models.Index(
                fields=["organisation", "status"], name="compliance__organis_0c516b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="complianceobligation",
            constraint=models.UniqueConstraint(
                fields=("organisation", "rule", "due_date"),
                name="unique_obligation_instance",
            ),
        ),
    ]
