# Generated by Django 5.2.16 on 2026-08-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0002_membershipapplication_network"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="membershipapplication",
            new_name="memberships_network_fa9b48_idx",
            old_name="memberships_network_c78d99_idx",
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="motivation",
            field=models.TextField(
                blank=True, help_text="Why this organisation is applying to join."
            ),
        ),
    ]
