# Generated by Django 5.2.16 on 2026-08-12 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0003_fix_network_index_and_motivation_help_text"),
        ("networks", "0001_initial"),
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="membershipapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["draft", "submitted", "information_requested", "approved"],
                    )
                ),
                fields=("organisation", "network"),
                name="unique_active_application_per_organisation_network",
            ),
        ),
    ]
