# Generated by Django 5.2.16 on 2026-07-23 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("governance", "Governance"),
                            ("finance", "Finance"),
                            ("hr", "Human Resources"),
                            ("safeguarding", "Safeguarding / Child Protection"),
                            ("popia", "POPIA / Data Protection"),
                            ("procurement", "Procurement"),
                            ("health_safety", "Health & Safety"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        help_text="Role or person accountable for this policy",
                        max_length=255,
                    ),
                ),
                (
                    "approval_authority",
                    models.CharField(
                        blank=True, help_text="e.g. Board of Directors", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("under_review", "Under Review"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("applicable_programmes", models.JSONField(blank=True, default=list)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Policies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "version_number"),
                        name="unique_policy_version",
                    )
                ],
            },
        ),
    ]
