# Generated by Django 5.2.16 on 2026-07-23 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(max_length=255)),
                ("trading_name", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "organisation_type",
                    models.CharField(
                        choices=[
                            ("npo", "NPO"),
                            ("network", "NPO Network / Umbrella Body"),
                            ("association", "Association"),
                            ("foundation", "Foundation"),
                            ("funder", "Funder"),
                        ],
                        default="npo",
                        max_length=20,
                    ),
                ),
                ("founding_date", models.DateField(blank=True, null=True)),
                (
                    "financial_year_end",
                    models.CharField(
                        blank=True, help_text="MM-DD, e.g. 02-28", max_length=5
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("website", models.URLField(blank=True)),
                ("physical_address", models.TextField(blank=True)),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EC", "Eastern Cape"),
                            ("FS", "Free State"),
                            ("GP", "Gauteng"),
                            ("KZN", "KwaZulu-Natal"),
                            ("LP", "Limpopo"),
                            ("MP", "Mpumalanga"),
                            ("NC", "Northern Cape"),
                            ("NW", "North West"),
                            ("WC", "Western Cape"),
                        ],
                        max_length=3,
                    ),
                ),
                ("municipality", models.CharField(blank=True, max_length=150)),
                (
                    "areas_of_operation",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of provinces/municipalities served",
                    ),
                ),
                (
                    "legal_structure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("npc", "Non-Profit Company (NPC)"),
                            ("trust", "Trust"),
                            ("voluntary_association", "Voluntary Association"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("dsd_registered", models.BooleanField(blank=True, null=True)),
                ("dsd_npo_number", models.CharField(blank=True, max_length=50)),
                ("cipc_registered", models.BooleanField(blank=True, null=True)),
                (
                    "cipc_registration_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("sars_pbo_approved", models.BooleanField(blank=True, null=True)),
                ("sars_pbo_number", models.CharField(blank=True, max_length=50)),
                ("section18a_approved", models.BooleanField(blank=True, null=True)),
                ("section18a_number", models.CharField(blank=True, max_length=50)),
                (
                    "masters_office_registered",
                    models.BooleanField(blank=True, null=True),
                ),
                ("masters_office_number", models.CharField(blank=True, max_length=50)),
                ("sectors", models.JSONField(blank=True, default=list)),
                ("programme_areas", models.JSONField(blank=True, default=list)),
                ("beneficiary_groups", models.JSONField(blank=True, default=list)),
                ("sensitive_service_areas", models.JSONField(blank=True, default=list)),
                (
                    "onboarding_step",
                    models.CharField(
                        choices=[
                            ("identity", "Organisation Identity"),
                            ("legal", "Legal Structure"),
                            ("registration", "Registration Status"),
                            ("governance", "Governance"),
                            ("activities", "Activities"),
                            ("compliance", "Compliance Profile"),
                            ("health_check", "Health Check"),
                            ("complete", "Onboarding Complete"),
                        ],
                        default="identity",
                        max_length=20,
                    ),
                ),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_publicly_listed", models.BooleanField(default=False)),
                (
                    "public_verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("public_about", models.TextField(blank=True)),
                (
                    "public_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organisation_logos/"
                    ),
                ),
                ("public_show_impact", models.BooleanField(default=True)),
                ("public_show_contact", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organisations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["legal_name"],
            },
        ),
        migrations.CreateModel(
            name="OrganisationMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("org_admin", "Organisation Administrator"),
                            ("executive_director", "Executive Director / CEO"),
                            ("board_member", "Board Member"),
                            ("treasurer", "Treasurer"),
                            ("compliance_officer", "Compliance Officer"),
                            ("project_manager", "Project Manager"),
                            ("me_officer", "M&E Officer"),
                            ("finance_officer", "Finance Officer"),
                            ("staff", "Staff Member"),
                            ("volunteer", "Volunteer"),
                        ],
                        default="staff",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships_invited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisation_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(
                fields=["province"], name="organisatio_provinc_b8bd17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(
                fields=["organisation_type"], name="organisatio_organis_6c6665_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(
                fields=["is_publicly_listed"], name="organisatio_is_publ_e1fd5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organisationmembership",
            index=models.Index(
                fields=["user", "is_active"], name="organisatio_user_id_292a58_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationmembership",
            constraint=models.UniqueConstraint(
                fields=("organisation", "user"), name="unique_org_membership"
            ),
        ),
    ]
