# Generated by Django 5.2.16 on 2026-07-23 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        ("programmes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("named", "Named Beneficiary"),
                            ("attendance_participant", "Attendance Participant"),
                        ],
                        default="attendance_participant",
                        max_length=25,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=30)),
                ("contact_number", models.CharField(blank=True, max_length=32)),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Enhanced access restrictions apply (spec section 26)",
                    ),
                ),
                ("consent_recorded", models.BooleanField(default=False)),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        help_text="Internal reference, not a government ID number",
                        max_length=40,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaries",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaries",
                        to="programmes.programme",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Beneficiaries",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
